baseURL: https://disha-javur-portfolio.netlify.app/
languageCode: en-us
title: Portfolio of Disha Javur
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A BEAUTIFUL WEBSITE CREATED BY ME AND RELEASED BECAUSE IT'S A PART OF MY ASSIGNMENT. HAVE FUN EXPLORING!
    title: Hi, my name is Disha. Welcome to my Portfolio!
  blog: {}
  contact: 
    address:
      - city: London, ST NW1 6BS
        country: United Kingdom
        street: Ivor Court, Gloucester Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: djavur.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7774985345
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: The Disha Daily Co.
    enable: yes
    # quicklinks:
    #   - alt: HTML5 UP
    #     text: 'Design: '
    #     url: https://www.html5up.net
    social:
      #- icon: fa-twitter
      #  label: Twitter
       # url: https://www.twitter.com
      #- icon: fa-facebook
       # label: Facebook
       # url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/dishajavur/?hl=en
      - icon: fa-github
        label: GitHub
        url: https://github.com/DJavur
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/disha-javur-857695183/
  image: ''
  name: Your name
  navigation:
    button1:
    #   - name: Get Started
    #     url: blogs
    # button2:
    #   - name: Log In
    #     url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      # - name: Generic Blog
      #   url: blogs/ipsum
      # - name: Elements
      #   url: elements.html
    menu: Menu
    subtitle: Portfolio website
    title: Disha Javur's
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpeg
        subtitle: A look at my academics, extracurriculars and professional achievements
        title: My Resume
        url: https://drive.google.com/file/d/13fm72R-787M34Gv7PEwAWuMhrDz1_L4R/view?usp=sharing
      - image: me_london.jpeg
        subtitle: Click here to find out more
        title: A little about me
        url: blogs/about_me
      - image: rent_sf.jpeg
        subtitle: More about the rental analysis project
        title: San Fransisco Rent Analysis
        url: blogs/rentsf
      - image: imdb.jpeg
        subtitle: More about the movies analysis project
        title: IMDB Movies Analysis
        url: blogs/ipsum
      # - image: pic05.jpg
      #   subtitle: Ipsum Dolor Sit Amet
      #   title: Project 5
      #   url: blogs/ipsum
      # - image: pic06.jpg
      #   subtitle: Feugiat Amet Tempus
      #   title: Project 6
      #   url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "My experience during my undergraduate studies and as an analyst has broadened my knowledge in terms of business and people skills. \n 
    Through my work in one of the fastest-growing AI and analytics startups in India, 
    I believe my cross-functional work experiences working for clients from across the globe have helped me build on my management and strategic skills. \n 
    During my time at TheMathCompany, working directly with clients to handle their day-to-day triggers and optimizing their existing models gave me a deeper 
    understanding of multiple fields under marketing and customer acquisition. \n 
    I believe my experiences in a start-up will be my key contributors in this everchanging entrepreneurial world. \n 
    My ability to get into any role during the need of the hour has made me more open-minded and helped me understand how to make the best of an opportunity. \n 
    I aim to bring this go-getter attitude, entrepreneurial spirit to the program and also wish to 
    learn from the experiences of my peers. "
    title: How my past experiences have shaped me
    url: blogs
