baseURL: https://disha-javur-portfolio.netlify.app/
languageCode: en-us
title: Portfolio of Disha Javur
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Disha. Welcome to my Portfolio!
  blog: {}
  contact: 
    address:
      - city: London, ST NW1 6BS
        country: United Kingdom
        street: Ivor Court, Gloucester Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: djavur.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7774985345
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: The Disha Daily Co.
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
      #  label: Twitter
       # url: https://www.twitter.com
      #- icon: fa-facebook
       # label: Facebook
       # url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/dishajavur/?hl=en
      - icon: fa-github
        label: GitHub
        url: https://github.com/DJavur
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/disha-javur-857695183/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpeg
        subtitle: My Resume
        title: Project 1
        url: blogs/aliquam
      - image: scooby_pic.jpeg
        subtitle: A little about me
        title: Project 2
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Project 3
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Project 4
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Project 5
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Project 6
        url: blogs/ipsum
  two:
    # buttonText: Get Started
    # enable: yes
    # subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
    #   \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
    #   condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
    #   pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
    #   Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
    #   amet pharetra et feugiat tempus."
    # title: Massa libero
    # url: blogs
